# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nE4VNmf6fEXdHTkX-v0hYP0jhchvTkWL
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('datset - Sheet1.csv')
df.head()

# Check for null values
print(df.isnull().sum())

# drop null value. if the null value impact on our data then we use df.fillna(method='ffill') depending on the context
df.dropna(inplace=True)

# Sum of sales by region
sales_by_region = df.groupby('Region')['TotalSales'].sum()
print(sales_by_region)

# Average sales per product
avg_sales_per_product = df.groupby('Product')['TotalSales'].mean()
print(avg_sales_per_product)

# Highest & lowest selling products
product_sales = df.groupby('Product')['TotalSales'].sum()
highest_selling_product = product_sales.idxmax()
lowest_selling_product = product_sales.idxmin()
print("Highest selling product:", highest_selling_product)
print("Lowest selling product:", lowest_selling_product)

# Use NumPy to calculate mean, median, standard deviation of numerical fields.

import numpy as np
mean_sales = np.mean(df['TotalSales'])
median_sales = np.median(df['TotalSales'])
std_sales = np.std(df['TotalSales'])

print(f"Mean Sales: {mean_sales}")
print(f"Median Sales: {median_sales}")
print(f"Standard Deviation of Sales: {std_sales}")







































